# Generated by Django 5.1.7 on 2025-04-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='phone',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, to='store.product')),
            ],
        ),
    ]
